<a href="https://colab.research.google.com/github/SeanMuInCa/learn_python/blob/master/assign2_000506980.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data = np.random.randint(-100,101,size=(20,5))
data

array([[ -39,  -29,   42,  -76,   -2],
       [  41,  -94,  -54,  -27,    0],
       [  99,  -91,  -17,   41,   23],
       [  -4,  -15,    4,   39,  -47],
       [  25,  -65,   34,  -85,  -91],
       [  53,  -69,  -18,  -39,    2],
       [ -66,   72,  100,   41,   61],
       [ -58, -100,   46,   -7,  -52],
       [  95,   84,   99,  -71,  -46],
       [  94,   48,  -42,   77,   67],
       [  29,   98,   40,  -95,   21],
       [ -89,   86,   48,   64,  100],
       [  64,   42,   47,    5,   14],
       [ -59,   68,  -41,  -26,   -3],
       [  43,  -31,  -98,  -57,  -90],
       [   8,  -22,  -26,  -43,  -89],
       [ -98,   60,  -43,   20,   65],
       [ -87,  -85,   23,   95,   35],
       [ -12,   27,   89,   46,   51],
       [   1,  -82,  -91,   -2,  -28]])

In [ ]:
np.average(data[:,2])

7.1

In [ ]:
np.sum(data[:5])

-388

In [ ]:
np.average(data[:3, 3])

-20.666666666666668

In [ ]:
newData = data[1][1:]
newData

array([-94, -54, -27,   0])

In [ ]:
data = data.reshape(10,10)
data

array([[ -39,  -29,   42,  -76,   -2,   41,  -94,  -54,  -27,    0],
       [  99,  -91,  -17,   41,   23,   -4,  -15,    4,   39,  -47],
       [  25,  -65,   34,  -85,  -91,   53,  -69,  -18,  -39,    2],
       [ -66,   72,  100,   41,   61,  -58, -100,   46,   -7,  -52],
       [  95,   84,   99,  -71,  -46,   94,   48,  -42,   77,   67],
       [  29,   98,   40,  -95,   21,  -89,   86,   48,   64,  100],
       [  64,   42,   47,    5,   14,  -59,   68,  -41,  -26,   -3],
       [  43,  -31,  -98,  -57,  -90,    8,  -22,  -26,  -43,  -89],
       [ -98,   60,  -43,   20,   65,  -87,  -85,   23,   95,   35],
       [ -12,   27,   89,   46,   51,    1,  -82,  -91,   -2,  -28]])

In [ ]:
res = np.std(data)
res

60.03321997027979

In [ ]:
data = np.sort(data)
row_means = np.mean(data, axis=1)
data[:,-1] = row_means
data

array([[ -94,  -76,  -54,  -39,  -29,  -27,   -2,    0,   41,  -23],
       [ -91,  -47,  -17,  -15,   -4,    3,    4,   23,   39,   -6],
       [ -91,  -85,  -69,  -65,  -39,  -18,    2,   25,   34,  -25],
       [-100,  -66,  -58,  -52,   -7,   41,   46,   61,   72,    3],
       [ -71,  -46,  -42,   48,   67,   77,   84,   94,   95,   40],
       [ -95,  -89,   21,   29,   40,   48,   64,   86,   98,   30],
       [ -59,  -41,  -26,   -3,    5,   14,   42,   47,   64,   11],
       [ -98,  -90,  -89,  -57,  -43,  -31,  -26,  -22,    8,  -40],
       [ -98,  -87,  -85,  -43,   20,   23,   35,   60,   65,   -1],
       [ -91,  -82,  -28,  -12,   -2,    1,   27,   46,   51,    0]])

In [ ]:
row1 = np.random.randint(0,10)
row2 = np.random.randint(0,10)

newDataContainsRandomTwoRows = np.stack((data[row1], data[row2]))
newDataContainsRandomTwoRows

array([[-98, -87, -85, -43,  20,  23,  35,  60,  65,  -1],
       [-98, -87, -85, -43,  20,  23,  35,  60,  65,  -1]])

In [ ]:
col1 = np.random.randint(0,10)
col2 = np.random.randint(0,10)
col3 = np.random.randint(0,10)
newDataContainsRandomThreeCols = np.stack((data[:,col1], data[:,col2],data[:,col3]),axis=1)
newDataContainsRandomThreeCols
#

array([[ -2, -27,  -2],
       [  4,   3,   4],
       [  2, -18,   2],
       [ 46,  41,  46],
       [ 84,  77,  84],
       [ 64,  48,  64],
       [ 42,  14,  42],
       [-26, -31, -26],
       [ 35,  23,  35],
       [ 27,   1,  27]])

In [ ]:
randomDoubles = np.random.normal(loc=0, scale=1, size=100)
randomDoubles

array([-1.83470741, -0.01581429,  0.36834268,  0.16488997, -1.76565991,
        1.15293345,  0.17584813,  0.02375794, -0.13498007, -0.0323277 ,
        0.04744031,  0.64241687, -0.5142113 , -0.28094153, -0.06899241,
       -0.71613362,  0.07128101,  0.48561153,  2.55831661, -0.58522452,
       -0.53882686, -0.59341105, -0.26762759,  0.35342379,  0.71277077,
        1.48029051,  0.7059861 , -2.61493975, -0.9889974 ,  0.93878318,
       -1.77656445,  0.0334316 ,  0.52362443,  0.69410113, -0.24059641,
        0.44468223, -2.04212989,  0.18936361,  0.42750857,  0.12636063,
        1.11751038, -0.06441011, -1.1421086 ,  0.52905866, -0.17658711,
        0.75829627, -1.69074379,  0.34133731, -0.08931529, -0.7669924 ,
        0.14010236,  0.8098253 ,  0.06717642, -0.78865944, -1.8278073 ,
        1.32048682, -1.78634595, -0.5299876 ,  0.68052799,  1.43654397,
        1.23124888, -1.86001514, -0.94277125, -0.77016415, -1.29341927,
        0.31903745,  0.89271922,  0.33695218,  0.35481162,  0.05

In [ ]:
import pandas as pd
dataframe = pd.DataFrame(data)
dataframe.columns = ['a','b','c','d','e','f','g','h','i','j']
dataframe.describe()

a          b          c          d          e          f  \
count   10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   -88.800000 -70.900000 -44.700000 -20.900000   0.800000  13.100000   
std     13.248061  19.461929  33.599107  37.569048  34.621124  34.875811   
min   -100.000000 -90.000000 -89.000000 -65.000000 -43.000000 -31.000000   
25%    -97.250000 -86.500000 -66.250000 -49.750000 -23.500000 -13.250000   
50%    -92.500000 -79.000000 -48.000000 -27.000000  -3.000000   8.500000   
75%    -91.000000 -51.750000 -26.500000  -5.250000  16.250000  36.500000   
max    -59.000000 -41.000000  21.000000  48.000000  67.000000  77.000000   

               g          h          i          j  
count  10.000000  10.000000  10.000000  10.000000  
mean   27.600000  42.000000  56.700000  -1.100000  
std    33.447139  36.325687  27.904798  24.515075  
min   -26.000000 -22.000000   8.000000 -40.000000  
25%     2.500000  23.500000  39.500000 -18.750000  
50%    31.000000  46.500000  57.500000  -0.500000  
75%    45.000000  60.750000  70.250000   9.000000  
max    84.000000  94.000000  98.000000  40.000000

In [ ]:
pd.to_excel('assign1.xlsx', dataframe)

In [ ]:
pd.to_csv('assign1.xlsx', dataframe)

In [ ]:
dataframe[dataframe < 0] = 0
dataframe

a  b   c   d   e   f   g   h   i   j
0  0  0   0   0   0   0   0   0  41   0
1  0  0   0   0   0   3   4  23  39   0
2  0  0   0   0   0   0   2  25  34   0
3  0  0   0   0   0  41  46  61  72   3
4  0  0   0  48  67  77  84  94  95  40
5  0  0  21  29  40  48  64  86  98  30
6  0  0   0   0   5  14  42  47  64  11
7  0  0   0   0   0   0   0   0   8   0
8  0  0   0   0  20  23  35  60  65   0
9  0  0   0   0   0   1  27  46  51   0

In [ ]:
dataframe[dataframe == 0] = 1
dataframe

a  b   c   d   e   f   g   h   i   j
0  1  1   1   1   1   1   1   1  41   1
1  1  1   1   1   1   3   4  23  39   1
2  1  1   1   1   1   1   2  25  34   1
3  1  1   1   1   1  41  46  61  72   3
4  1  1   1  48  67  77  84  94  95  40
5  1  1  21  29  40  48  64  86  98  30
6  1  1   1   1   5  14  42  47  64  11
7  1  1   1   1   1   1   1   1   8   1
8  1  1   1   1  20  23  35  60  65   1
9  1  1   1   1   1   1  27  46  51   1

In [ ]:
# -*- coding: utf-8 -*-

# Sample Python code for youtube.search.list
# See instructions for running these code samples locally:
# https://developers.google.com/explorer-help/code-samples#python

import os

import google_auth_oauthlib.flow
import googleapiclient.discovery
import googleapiclient.errors

scopes = ["https://www.googleapis.com/auth/youtube.readonly"]

def main():
    # Disable OAuthlib's HTTPS verification when running locally.
    # *DO NOT* leave this option enabled in production.
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

    api_service_name = "youtube"
    api_version = "v3"
    client_secrets_file = "YOUR_CLIENT_SECRET_FILE.json"

    # Get credentials and create an API client
    flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file(
        client_secrets_file, scopes)
    credentials = flow.run_console()
    youtube = googleapiclient.discovery.build(
        api_service_name, api_version, credentials=credentials)

    request = youtube.search().list(
        part="snippet",
        maxResults=25,
        q="surfing"
    )
    response = request.execute()

    print(response)

if __name__ == "__main__":
    main()

FileNotFoundError: [Errno 2] No such file or directory: 'YOUR_CLIENT_SECRET_FILE.json'

In [ ]:
import json
from openai import OpenAI

client = OpenAI(
    api_key="sk-4e98eb1df2dc496dbf9cf38f1aa8320e",
    base_url="https://api.deepseek.com",
)

system_prompt = """
You are a resume parser. The user will provide raw resume text.
Please extract the following fields and output as a JSON object:
- name
- email
- phone
- education (list of strings)
- skills (list of strings)

Return ONLY valid JSON.
"""

user_prompt = """TAI CONG CHI NGUYEN (JOSEPH)  Saskatoon,  Saskatchewan | 6399983636 | taincc@gmail.c o m | linkedin.com/in/joseph - tainguyen  I  will be graduating  from  Artificial Intelligence and Data Analytics  Post - Graduate Certificate at Saskatchewan Polytechnic and seeking a  Full - time opportunity in Canada. I have been  working  for over 10 years. About 3 years ago, I became interested in the field of  machine  learning,  data engineering  and  business intelligence  then I started focusing my skills on data as well. I am passionate about  understanding user problems and solving them with available resources in the organization.  PROFESSIONAL  WORK  EXPERIENCE  Digital Integration Centre of Excellence (DICE)  ●  Research Assistant  June 2024  -  Present  o  Leverage  machine learning and  geospatial data  to  identify  potential gravel pits  o  Support data collection, cleaning, and preprocessing to prepare for analysis and model development  o  Train  and  test  machine learning models, such as ResNet, VGG16, and Random Forest, using satellite images, hillshade images,  and numerical datasets  o  Contribute to the creation and maintenance  of  PostgreSQL  database  o  Assist in designing visualizations and presenting key findings to partners  TMAM  Project  ●  Part - time Freelancer  January 2024  –  March 2024  o  Develop and maintain a web crawler using Python  o  ETL and  store crawled data  to  MongoDB  and  PostgreSQL  Geniebook  ●  Senior Engineer  April 2022  –  July 2023  o  Design and implement a real - time data pipeline to process structured data from many data sources using Kafka, ksqlDB,  Python and stored processed data in Cassandra  o  Migrate data from MySQL to PostgreSQL for Microservice and Odoo databases  o  Develop Google Forms and use Apps Script to automatically notification from Google Sheets  Amaris Consulting  -  Bolloré Transport & Logistics  -  Mizuho Bank  -  FPT Information System  ●  Experienced Consultant  –  Senior Database Developer  –  Senior Officer  –  Software Developer  September  20 09  –  April 2022  o  Confer with system analysts, developers, and other teams to translate business requirements into data modeling, database  design, efficient SQL for fast application performance  o  Enhancement of existing data migration and consolidation between various databases  o  Troubleshoot database performance related and tune complex database queries  o  Responsible for development and  maintenance of the  core banking system and operating database  o  Participated in development RPA using UIPath  o  Have knowledge of SQL Data Warehouse, ETL by SSIS and Power BI Desktop  o  Expertise in development using  MS SQL Server  and  Oracle PL/SQL  EDUCATION  Saskatchewan Polytechnic  ●  Postgraduate in Artificial Intelligence and Data Analytics  Expected  April 202 5  ●  Postgraduate in Cloud  Computing & Blockchain  April 2024  o  Award:  Saskatchewan Polytechnic Dean ’ s Honour List  University of Greenwich  ●  Bachelor of Science in Computing  20 20  National Institute of IT  ●  Diploma in Software Engineering  2009  CERTIFICATIONS  ●  Machine Learning, Deep Learning + AWS Sagemaker , Udemy  January 2025  ●  RPA  -  Process Automation using UIPATH  -  Beginner to Expert ,  Udemy  April 2022  ●  Master in Microsoft Power BI Desktop and Service ,  Udemy  March 2022  ●  Data Warehouse Developer - SQL Server/ETL/SSIS/SSAS/SSRS/T - SQL , Udemy  March 2022  A DDITIONAL  INFORMATION  ●  Languages:  Vietnamese (native),  English  (conversational proficiency)  ●  Programming Languages:  Python ,  .Net, SQL  ●  Databases:  Oracle, MS SQL, MySQL, PostgreSQL, MongoDB, Cassandra  ●  Stream processing:  Apache Kafka  ●  Cloud Services:  AWS
"""

messages = [{"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}]

response = client.chat.completions.create(
    model="deepseek-chat",
    messages=messages,
    response_format={
        'type': 'json_object'
    }
)

print(json.loads(response.choices[0].message.content))

{'name': 'TAI CONG CHI NGUYEN (JOSEPH)', 'email': 'taincc@gmail.com', 'phone': '6399983636', 'education': ['Postgraduate in Artificial Intelligence and Data Analytics, Saskatchewan Polytechnic, Expected April 2025', 'Postgraduate in Cloud Computing & Blockchain, Saskatchewan Polytechnic, April 2024', 'Bachelor of Science in Computing, University of Greenwich, 2020', 'Diploma in Software Engineering, National Institute of IT, 2009'], 'skills': ['Machine Learning', 'Data Engineering', 'Business Intelligence', 'PostgreSQL', 'Python', 'MongoDB', 'Kafka', 'ksqlDB', 'Cassandra', 'MySQL', 'Google Apps Script', 'SQL', 'ETL', 'SSIS', 'Power BI', 'MS SQL Server', 'Oracle PL/SQL', 'UIPath', 'AWS Sagemaker', 'Apache Kafka', 'AWS', 'Vietnamese', 'English', '.Net', 'Stream processing']}
